// src/lib/components/FileTree.svelte
<script lang="ts">
    import type { ProjectFile, ProjectFolder } from '../projects';
    import Fa from './Fa.svelte';
    import FileTree from './FileTree.svelte';

    interface Props {
        items: (ProjectFile | ProjectFolder)[];
        onFileClick: (file: ProjectFile) => void;
        selectedFile: ProjectFile | null;
        depth?: number; // Tracks how far to indent
    }

    let { items, onFileClick, selectedFile, depth = 0 }: Props = $props();
</script>

<ul class="space-y-1">
    {#each items as item (item.name)}
        <li style:padding-left="{depth * 12}px">
            {#if item.type === 'folder'}
                <div>
                    <div class="flex items-center gap-2 p-2 text-gray-400 text-[11px] font-bold uppercase tracking-widest">
                        <span>📁</span> {item.name}
                    </div>
                    <!-- This is the Recursion: The component renders itself for the children -->
                    <FileTree items={item.children} {onFileClick} {selectedFile} depth={depth + 1} />
                </div>
            {:else}
                <button
                    type="button"
                    onclick={() => onFileClick(item)}
                    class="flex items-center gap-2 p-2 rounded-lg cursor-pointer text-sm font-medium transition-colors w-min text-left {selectedFile === item
                        ? 'bg-blue-50 text-blue-600'
                        : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-white/5'}"
                >
                    <span><Fa icon={item.icon} /></span>{item.name}
                </button>
            {/if}
        </li>
    {/each}
</ul>

// src/FileTree.tsx
import React from 'react';
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";

interface FileTreeProps {
    items: any[];
    onFileClick: (file: any) => void;
    selectedFile: string | null;
    depth?: number; // Tracks how far to indent
}

const FileTree: React.FC<FileTreeProps> = ({ items, onFileClick, selectedFile, depth = 0 }) => {
    return (
        <ul className="space-y-1">
            {items.map((item) => (
                <li key={item.name} style={{ paddingLeft: `${depth * 12}px` }}>
                    {item.type === 'folder' ? (
                        <div>
                            <div className="flex items-center gap-2 p-2 text-gray-400 text-[11px] font-bold uppercase tracking-widest">
                                <span>📁</span> {item.name}
                            </div>
                            {/* This is the Recursion: The component calls itself for the children */}
                            <FileTree
                                items={item.children}
                                onFileClick={onFileClick}
                                selectedFile={selectedFile}
                                depth={depth + 1}
                            />
                        </div>
                    ) : (
                        <div
                            onClick={() => onFileClick(item)}
                            className={`flex items-center gap-2 p-2 rounded-lg cursor-pointer text-sm font-medium transition-colors w-min ${
                                selectedFile === item.name
                                    ? 'bg-blue-50 text-blue-600'
                                    : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-white/5'
                            }`}
                        >
                            <span><FontAwesomeIcon icon={item.icon} /></span>{item.name}
                        </div>
                    )}
                </li>
            ))}
        </ul>
    );
};

export default FileTree;
